esphome:
  name: backdoorlight2
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip: 
    static_ip: !secret ip
    gateway: !secret gateway
    subnet: !secret subnet

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Backdoorlight2 Fallback Hotspot"
    password: !secret fallback_hotspot_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret API_password

ota:
  password: !secret OTA_password

output:
  - platform: gpio
    id: back_door_light_relay
    pin: 4
  
light: 
  - platform: binary
    id: back_door_light
    name: "Back Door Light"
    output: back_door_light_relay
  
binary_sensor:
  - platform: gpio
    pin: 5
    id: back_door_light_wall_switch
    on_state:
      - light.toggle: back_door_light