esphome:
  name: guestbathroomfan2
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip: 
    static_ip: !secret IP
    gateway: !secret gateway
    subnet: !secret subnet

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Guestbathroomfan2"
    password: !secret fallback_hotspot_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret API_password

ota:
  password: !secret OTA_password

output:
  - platform: gpio
    id: guest_bath_room_fan_relay
    pin: 4
  
fan:
  - platform: binary
    id: guest_bath_room_fan
    name: "Guest Bath Room Fan"
    output: guest_bath_room_fan_relay
  
binary_sensor:
  - platform: gpio
    pin: 5
    id: guest_bath_room_fan_wall_switch
    on_state:
      - fan.toggle: guest_bath_room_fan