esphome:
  name: livingroommini2
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret IP
    gateway: !secret gateway
    subnet: !secret subnet

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Living Room Mini 2 Hotspot"
    password: !secret fallback_hotspot_password

captive_portal:
logger:
api:
  password: !secret API_password
  
ota:
  password: !secret OTA_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Living Room Mini 2 Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Living Room Mini 2 Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes