#config for MQTT in HA:
#binary_sensor:
#  - state_topic: "mailbox/status"
#    device_class: opening
#    payload_on: "online"
#    payload_off: "offline"
#    name: "Mailbox"
esphome:
  name: mailbox
  on_boot:
    priority: 900
    then:
      - lambda: |-
          id(wake_up_reason) = esp_sleep_get_wakeup_cause();
esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

ota:
  password: !secret OTA_password

wifi:
  manual_ip:
    static_ip: !secret IP
    gateway: !secret gateway
    subnet: !secret subnet
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mailbox Fallback Hotspot"
    password: !secret fallback_hotspot_password

captive_portal:

globals:
  - id: wake_up_reason
    type: int
    restore_value: no
    initial_value: '0'

deep_sleep:
  run_duration: 10s #10s
  id: deep_sleep_1
  sleep_duration:
    days: 365
  wakeup_pin:
    number: GPIO27
  #wakeup_pin_mode: INVERT_WAKEUP
    
mqtt:
  broker: !secret HA_IP
  username: !secret mqttuser
  password: !secret mqttpassword
  discovery: false
  discovery_retain: false
  on_message:
    - topic: mailbox/ota_update
      payload: 'ON'
      then:
        - deep_sleep.prevent: deep_sleep_1
    - topic: mailbox/sleep_mode
      payload: 'ON'
      then:
        - deep_sleep.enter: deep_sleep_1

sensor:
  - platform: template
    name: "Wake-up Reason"
    accuracy_decimals: 0
    internal: true
    lambda: |-
      return (id(wake_up_reason));

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO27
      mode: INPUT_PULLDOWN
      inverted: true
    name: Mailbox
    internal: true
    device_class: opening
    
    