esphome:
  name: proofercontroller

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret OTA_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Proofercontroller"
    password: !secret hotspot_password

captive_portal:

switch:
  - platform: gpio
    name: heatmat
    id: heatmat
    pin: GPIO0
    
dallas:
  - pin: GPIO16
    update_interval: 10s
i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true
  id: bus_a
  
sensor:
  - platform: bme280
    i2c_id: bus_a
    temperature:
      name: "Proofer Ambient Temperature"
      oversampling: 16x
    pressure:
      name: "Proofer Ambient Pressure"
    humidity:
      name: "Proofer Ambient Humidity"
    address: 0x76
    update_interval: 10s
  - platform: dallas
    address: !secret address
    id: proofer_temp
    name: "Proofer temperature"
    

  
climate:
  - platform: thermostat
    name: "Proofer Thermostat"
    sensor: proofer_temp
    min_heating_off_time: 5s
    min_heating_run_time: 5s
    min_idle_time: 5s
    default_mode: heat
    heat_action:
      - switch.turn_on: heatmat
    idle_action:
      - switch.turn_off: heatmat
    default_target_temperature_low: 26
    visual:
      min_temperature: 0
      max_temperature: 200
      temperature_step: 1