esphome:
  name: smartlightswitch
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret IP
    gateway: !secret gateway
    subnet: !secret subnet

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Smartlightswitch"
    password: !secret hotspot_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

output:
  - platform: gpio
    id: smart_light_switch_relay
    pin: 4

light:
  - platform: binary
    id: smart_light_switch
    name: "Smart Light Switch"
    output: smart_light_switch_relay
        
binary_sensor:
  - platform: gpio
    pin: 5
    id: smart_light_switch_wall_switch
    on_state:
      - light.toggle: smart_light_switch